novells_site/core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views
from .models import Comment, LikeDislike, Chapter, Post, Review


app_name = 'core'

urlpatterns = [

    path('add_comment/to_chapter/<int:pk>', views.AddComment.as_view(model=Chapter), name='add_comment_to_chapter'),
    path('add_comment/to_post/<int:pk>', views.AddComment.as_view(model=Post), name='add_comment_to_post'),
    # path(''),
    path('', views.index, name='home'),
    path('contacts', views.contact, name='contacts'),
    path('novells_list/', views.NovellListView.as_view(), name='novell_list'),
    path('novells_list/filter/', views.FilterNovellsView.as_view(), name='filter'),
    path('news/', views.AllNewsView.as_view(), name='all_news'),
    path('new/<int:pk>/<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),

    path('add-rating/', views.AddNovellRating.as_view(), name='add_rating'),

    path('novells_list/json-filter/', views.JsonFilterNovellsView.as_view(), name='json_filter'),

    path('novell/<slug:slug>', views.NovellDetailView.as_view(), name='novell_detail'),
    path('profile/<int:pk>/<slug:slug>/', views.ProfileDetail.as_view(), name='profile_detail'),
    path('profile/edit/<int:pk>/<slug:slug>/', views.EditMyProfile.as_view(), name='edit_profile'),

    path('<str:slug>/chapter/<int:number>', views.ChapterDetailView.as_view(), name='chapter_detail'),

    path('api/get_notifications/', login_required(views.GetNotificationView.as_view()), name='get_notifications'),
    path('api/get_news/', login_required(views.GetNotificationNewsView.as_view()), name='get_news'),
    path('api/check_notifications/', login_required(views.CheckNotificationView.as_view()),
         name='check_notifications_all'),

    path('api/comment/<int:id>/like/',
         login_required(views.VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),
         name='comment_like'),
    path('api/comment/<int:id>/dislike/',
         login_required(views.VotesView.as_view(model=Comment, vote_type=LikeDislike.DISLIKE)),
         name='comment_dislike'),

    path('api/review/<int:id>/like/',
         login_required(views.VotesView.as_view(model=Review, vote_type=LikeDislike.LIKE)),
         name='comment_like'),
    path('api/review/<int:id>/dislike/',
         login_required(views.VotesView.as_view(model=Review, vote_type=LikeDislike.DISLIKE)),
         name='comment_dislike'),

    #  Добавление-удаление из закладок(избранного/запланированного)
    path('add_to_bookmark/novell/<int:pk>/<str:type_of>', views.add_to_bookmark, name='add_to_bookmarks'),
    path('delete_from_bookmark/novell/<int:pk>/<str:type_of>/<str:frommm>', views.del_from_bookmark,
         name='del_from_bookmarks'),


    path('novell_filter_test/', views.js_filter_test),
    path('api/nov_list/', views.NovellListViewApi.as_view()),

    path('buying_chapter/<int:pk>/', views.buy_chapter, name='buy_chapter'),

    path('buying_many_chapters/<int:pk>/', views.buy_many_chapters, name='buying_many_chapters'),

    path('pay_prepare', views.pay_prepare, name='pay_prepare'),

    path('donate_money', views.donate_money, name='donate_money'),

    # адресс вебхука
    path('payment-notification', csrf_exempt(views.my_webhook_handler)),
    
    path('admin/statistics', views.statistic_view),

]

novells_site/core/views.py
import json
from decimal import Decimal

from django.core.exceptions import PermissionDenied
from django.utils import timezone

from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.views import View
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DetailView, ListView
from django.contrib.auth.decorators import login_required

from .models import Novell, Chapter, LikeDislike, Profile, Genre, Rating, Slider, Post, Review, RatingStar, Comment, UserBalanceChange, ViewNovell
from .forms import CommentForm, EditProfileForm, RatingForm
from django.http import HttpResponse, JsonResponse, Http404, HttpResponseForbidden
from rest_framework import viewsets, filters, views
from rest_framework.response import Response
from .serializers import NovellListSerializer
import yookassa
import var_dump as var_dump
from yookassa.domain.models.currency import Currency
from yookassa.domain.models.receipt import Receipt
from yookassa.domain.models.receipt_item import ReceiptItem
from yookassa.domain.common.confirmation_type import ConfirmationType
from yookassa.domain.request.payment_request_builder import PaymentRequestBuilder
import json
from django.http import HttpResponse
from yookassa import Configuration, Payment
from yookassa.domain.notification import WebhookNotificationEventType, WebhookNotification
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
from datetime import date

# Create your views here.


#Configuration.account_id = '819176'
#Configuration.secret_key = 'live__QoWec5bBgd00kgqy4xnSz245AQk2faiTHjPJN7tkiQ' # Old key
#Configuration.secret_key = 'live_UaQb6za_zudoklGWzklf1GMIief0Yrhr7Q-YGtV-LsU'

# Configuration.account_id = '829811'
# Configuration.secret_key = 'test__QoWec5bBgd00kgqy4xnSz245AQk2faiTHjPJN7tkiQ'
# test_3z2IRsWt9h2FRrKVBy9AaGkeMHt6appEWllT9614G5k


@login_required
def pay_prepare(request):
    return render(request, 'core/include/pay_prepare.html')


@login_required
def donate_money(request):
    Configuration.account_id = '819176'
    Configuration.secret_key = 'live_Rj4b50yCpOzEirnhaHWgSJ_f-t9naP6WBSlAk8WlAss'

    #Configuration.account_id = '829811'
    #Configuration.secret_key = 'test_3z2IRsWt9h2FRrKVBy9AaGkeMHt6appEWllT9614G5k'


    # Configuration.configure('819176', 'test__QoWec5bBgd00kgqy4xnSz245AQk2faiTHjPJN7tkiQ')
    receipt = Receipt()
    receipt.customer = {"phone": "79990000000", "email": "test@email.com"}
    receipt.tax_system_code = 1
    receipt.items = [
        ReceiptItem({
            "description": "Пополнения баланса на сумму {}".format(request.POST.get('sum')),
            "quantity": 1,
            "amount": {
                "value": request.POST.get('sum'),
                "currency": Currency.RUB
            },
            "vat_code": 2,
            "capture":True
        }),
    ]

    s = {'user': str(request.user)}
    print(request.user)

    builder = PaymentRequestBuilder()
    builder.set_amount({"value": request.POST.get('sum'), "currency": Currency.RUB}) \
        .set_confirmation({"type": ConfirmationType.REDIRECT, "return_url": "https://privereda1.ru"}) \
        .set_capture(True) \
        .set_description("Заказ №72") \
        .set_metadata({"user": int(request.user.id)}) \
        .set_receipt(receipt)

    request = builder.build()
    # Можно что-то поменять, если нужно
    res = Payment.create(request)
    print(res.json())
    a = json.loads(res.json())
    print(a['confirmation']['confirmation_url'])
    var_dump.var_dump(res)
    # print(request.POST)
    # print(request.POST.get('sum'))
    return redirect(a['confirmation']['confirmation_url'])
    # return HttpResponse('Временно недоступен')


@csrf_exempt
def my_webhook_handler(request):
    Configuration.account_id = '819176'
    Configuration.secret_key = 'live_Rj4b50yCpOzEirnhaHWgSJ_f-t9naP6WBSlAk8WlAss'

    #Configuration.account_id = '829811'
    #Configuration.secret_key = 'test_3z2IRsWt9h2FRrKVBy9AaGkeMHt6appEWllT9614G5k'


    # Извлечение JSON объекта из тела запроса
    print(request)

    event_json = json.loads(request.body)
    print(event_json)
    try:
        # Создание объекта класса уведомлений в зависимости от события
        notification_object = WebhookNotification(event_json)
        response_object = notification_object.object
        if notification_object.event == WebhookNotificationEventType.PAYMENT_SUCCEEDED:
            payed_user = response_object.metadata['user']
            payed_money = response_object.amount.value
            # UserBalanceChange.objects.create(user=payed_user, amount=payed_money)
            print(payed_user, payed_money)
            p = Profile.objects.get(name_id=payed_user)
            p.balance += payed_money
            p.save(update_fields=['balance'])
            some_data = {
                'paymentId': response_object.id,
                'paymentStatus': response_object.status,
            }
            print(some_data)
    except Exception:
        # Обработка ошибок
        return HttpResponse(status=400)  # Сообщаем кассе об ошибке

    return HttpResponse(status=200)  # Сообщаем кассе, что все хорошо


def js_filter_test(request):
    return render(request, 'core/novells_list_new.html')


class GenreYear:

    def get_genres(self):
        return Genre.objects.all()

    def get_year(self):
        return Novell.objects.all().order_by('publish__year').values_list('publish__year').distinct()

    def get_status(self):
        return Novell.objects.all().values_list('status').distinct()


def contact(request):
    return render(request, 'core/contacts.html')


def index(request):

    h = request.get_host()
    if h == 'www.privereda1.ru' or h == 'privereda1.ru':
        pop_novell = Novell.objects.filter(important=True, translator='Privereda1')
        # pop_novell = Novell.objects.order_by('-views').first()
        test = pop_novell.first()
        shedule_chapter = Chapter.objects.filter(novell__translator='Privereda1').order_by('-created')[:8]
        all_novells = Novell.objects.filter(translator='Privereda1').order_by('-views')[:6]
        shots = Slider.objects.filter(active=True, translator='Privereda1').order_by('position')

        return render(request, 'core/home.html', {'pops': pop_novell,
                                                  'last_update': shedule_chapter,
                                                  'all_novells': all_novells,
                                                  'image_shots': shots,
                                                  'test': test
                                                  })
    else:
        pop_novell = Novell.objects.filter(important=True, translator='Oksiji13')
        # pop_novell = Novell.objects.order_by('-views').first()
        test = pop_novell.first()
        shedule_chapter = Chapter.objects.filter(novell__translator='Oksiji13').order_by('-created')[:8]
        all_novells = Novell.objects.filter(translator='Oksiji13').order_by('-views')[:6]
        shots = Slider.objects.filter(active=True, translator='Oksiji13').order_by('position')

        return render(request, 'core/home_second.html', {'pops': pop_novell,
                                                         'last_update': shedule_chapter,
                                                         'all_novells': all_novells,
                                                         'image_shots': shots,
                                                         'test': test
                                                         })

class NovellDetailView(GenreYear, DetailView):
    model = Novell
    context_object_name = 'novell'
    template_name = 'core/novell_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nov = context['novell']
        nov.views = nov.views + 1
        nov.save()
        if self.request.user.is_staff == False:
            ViewNovell.objects.create(novell = nov)
        context['star_form'] = RatingForm()

        return context

    def post(self, request, slug):
        data = request.POST
        novell = get_object_or_404(Novell, slug=slug)
        if request.user.is_anonymous or data['body'] is None:
            return redirect(novell.get_absolute_url())
        try:
            a = Review.objects.get(author=request.user, novell=novell)
            return redirect(novell.get_absolute_url())
        except:
            Review.objects.create(author=request.user, body=data['body'], title=data['title'], novell=novell)
        return redirect(novell.get_absolute_url())


class ChapterDetailView(DetailView):
    model = Chapter
    context_object_name = 'chapter'
    template_name = 'core/chapter_detail.html'

    def get_object(self):
        novell = get_object_or_404(Novell, slug=self.kwargs['slug'])
        chapter = get_object_or_404(Chapter, novell=novell, number=self.kwargs['number'])
        #

        if not self.request.user.is_anonymous:
            self.request.user.user_profile.chapter_readed.add(chapter)
        else:
            raise PermissionDenied
            #return redirect('accounts/signup/')
            #return redirect(novell.get_absolute_url())
            #return redirect('account_signup')


        if not chapter.premium:
            return chapter

        elif not self.request.user.is_anonymous and chapter not in self.request.user.user_profile.buyed_chapters.all():
            # "Вы пытаетесь открыть платную главу. Купите её, это не так дорого!"
            raise PermissionDenied
            #return redirect('accounts/signup/')
            #return redirect(novell.get_absolute_url())

        elif not self.request.user.is_anonymous and chapter in self.request.user.user_profile.buyed_chapters.all():
            return chapter
        else:

novells_site/templates/core/include/add_comment_form.html
{% load static %}


<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7 mt-3">
            {% if user.is_authenticated %}
                <div class="card bg-c-lite-unknown mb-2" style="border: 4px solid #a9d1f5; box-shadow: none;">
                    <form action="{% url 'core:add_comment_to_chapter' chapter.id %}" method="post"
                          id="CommentForm">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <div class="card-header">
                                <label for="contactcomment" class="editContent h6">
                                    Ваш комментарий:
                                </label>
                            </div>
                            <div class="card-body">
                            <textarea class="form-control border" rows="5" name="body"
                                      id="contactcomment" required=""></textarea>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-end w-100">
                                {% if request.get_host == 'www.oksiji13.ru' %}

                                    <button type="submit"
                                            class="mt-2 btn btn-outline-light"
                                            style="background-color: rgb(172,200,227)">
                                        Отправить
                                    </button>
                                {% else %}
                                    <button type="submit"
                                            class="mt-2 btn btn-outline-light"
                                            style="background-color: rgba(171,59,97,0.75)">
                                        Отправить
                                    </button>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            {% else %}
                <h5 class="text-center my-4">Войдите, чтобы оставить комментарий</h5>
            {% endif %}
        </div>
    </div>
</div>

novells_site/templates/core/include/footer.html
{% load static %}
<footer class="text-center text-lg-start d-flex justify-content-between" {% if request.get_host == 'www.oksiji13.ru' %}style="background: rgb(103,118,137)"{% else %}style="background: rgb(171,59,97);"{% endif %}>
    <!-- Copyright -->
    <div class="text-center p-2">

        <a href="https://vk.com/bl_novel_privereda1" style="text-decoration: none">
            <img src="{% static "img/icons/vk_belaya.png" %}" class="img-fluid" width="40">
        </a>

        <!--
        <a class="ml-2" href="https://tl.rulate.ru/users/169401">
            <img src="{% static "img/icons/ruletka.png" %}" width="40">
        </a>
-->


    </div>

    <ul class="nav mt-2">

        <li class="nav-item">
            <a href='{% url 'core:contacts' %}' class="nav-link link-light"><i
                    class="bi bi-person-lines-fill"></i>
                <span class="font-weight-bold">Контакты</span></a>
        </li>

        <li class="nav-item">
            <a href='https://vk.com/im?sel=-181277189' class="nav-link link-light">
                <i class="bi bi-question-circle"></i>
                <span class="font-weight-bold">Поддержка</span>
            </a>
        </li>


    </ul>

    <div class="font-weight-bold text-white p-3">
        © 2021
    </div>
    <!-- Copyright -->
</footer>

novells_site/templates/core/include/navbar.html
{% load user_tags %}
{% load static %}
<style>

</style>
<nav class="navbar navbar-expand-lg navbar-dark d-flex sticky-top py-0" style="background: rgb(171,59,97)">
    <div class="container-xxl pb-0 px-0">
        <a class="navbar-brand py-1" style="margin-right:0;" href="#"><img src="{% static "img/icons/logotip3.jpg" %}" width="250" height="50"></a>
        <a href="https://oksiji13.ru"><img style="height:32px;"src="{% static "/img/ban0.svg" %}" alt=""></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" aria-current="page" href='{% url 'core:home' %}'><i
                            class="bi bi-house-door"></i>
                        <span style="vertical-align: middle">Главная</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link font-weight-bold" aria-current="page" href='{% url 'core:filter' %}'>
                        <i class="bi bi-list"></i>
                        <span style="vertical-align: middle">Каталог новелл</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'core:all_news' %}"><i
                            class="bi bi-newspaper"></i>
                        <span style="vertical-align: middle">Новости</span>
                        {% if user.is_authenticated %}
                            <span class="badge bg-dark p-1 text-center" id="news-notification-count"
                                  style="vertical-align: middle;">{% if user|news_unchecked > 0 %}
                                {{ user|news_unchecked }}{% endif %}</span>
                        {% endif %}
                    </a>
                </li>
            </ul>


            {% if user.is_authenticated %}
                <div class="dropdown">

                    <button type="button" class="btn dropdown-toggle my-bell" data-action="check-notification"
                            data-bs-toggle="dropdown"
                            id="collapseNotification" aria-expanded="false" style="background-color: rgb(219,204,192)">
                        <i id="notify_icon"
                           class="h5 bi bi-bell-fill{% if user|count_unchecked > 0 %}text-success{% endif %}"></i>


                        <span class="badge bg-dark" id="notification-count">{% if user|count_unchecked > 0 %}
                            {{ user|count_unchecked }}{% endif %}</span>
                    </button>

                    <ul class="dropdown-menu" style="width: 500px;">
                        <div class="row justify-content-center">
                            {% not_list user %}
                        </div>
                    </ul>


                </div>
                <div class="mx-1">
                    <p class="m-0 text-center">
                        <a class="p-2 text-white" href="{{ user.user_profile.get_absolute_url }}">
                            {{ user.username }}
                        </a>
                    </p>
                    <p class="m-0 text-center">
                        <span style="font-size: 9pt">{{ user.user_profile.balance|floatformat:2 }} ₽ </span>
                        <a href="{% url 'core:pay_prepare' %}"> <i class="bi bi-patch-plus-fill text-success"></i></a>
                    </p>
                </div>

            {% else %}
                <a role="button" class="btn btn-outline-light border-0 mr-2" href="{% url 'account_signup' %}"
                   style="background-color: rgba(237,226,220,0.75);">Регистрация</a>
            {% endif %}

            {% if user.is_authenticated %}
                <button type="button" class="btn btn-outline-light mr-2 border-0" data-toggle="modal"
                        data-target="#logoutModal" style="background-color: rgb(18,61,106)">
                    Выход
                </button>
            {% else %}
                <button type="button" class="btn btn-outline-light border-0 mr-2" data-toggle="modal"
                        data-target="#loginModal" style="background-color: rgba(18,61,106,0.75);">
                    Вход
                </button>
            {% endif %}

            <form class="d-flex" action="{% url 'core:filter' %}" method="get" style="width: 23%">
                <input class="form-control mr-2" type="search" name="q" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-light border-0" type="submit" style="background-color: rgb(219,204,192)">
                    Поиск
                </button>
            </form>
        </div>


    </div>
</nav>

novells_site/templates/core/include/navbar_second.html
{% load user_tags %}
{% load static %}
<style>

</style>
<nav class="navbar navbar-expand-lg navbar-dark d-flex sticky-top py-0" style="background: rgb(103,118,137)">
    <div class="container-xxl pb-0 px-0">
        <a class="navbar-brand py-1" href="#"><img src="{% static "img/icons/logo_Oksiji13.png" %}" width="120" height="55"></a>
        <a href="https://privereda1.ru"><img style="height:32px;"src="{% static "/img/ban0.svg" %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" aria-current="page" href='{% url 'core:home' %}'><i
                            class="bi bi-house-door"></i>
                        <span style="vertical-align: middle">Главная</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link font-weight-bold" aria-current="page" href='{% url 'core:filter' %}'>
                        <i class="bi bi-list"></i>
                        <span style="vertical-align: middle">Каталог новелл</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'core:all_news' %}"><i
                            class="bi bi-newspaper"></i>
                        <span style="vertical-align: middle">Новости</span>
                        {% if user.is_authenticated %}
                            <span class="badge bg-dark p-1 text-center" id="news-notification-count"
                                  style="vertical-align: middle;">{% if user|news_unchecked > 0 %}
                                {{ user|news_unchecked }}{% endif %}</span>
                        {% endif %}
                    </a>
                </li>
            </ul>


            {% if user.is_authenticated %}
                <div class="dropdown">

                    <button type="button" class="btn dropdown-toggle my-bell" data-action="check-notification"
                            data-bs-toggle="dropdown"
                            id="collapseNotification" aria-expanded="false" style="background-color: rgb(172,200,227)">
                        <i id="notify_icon"
                           class="h5 bi bi-bell-fill{% if user|count_unchecked > 0 %}text-success{% endif %}"></i>


                        <span class="badge bg-dark" id="notification-count">{% if user|count_unchecked > 0 %}
                            {{ user|count_unchecked }}{% endif %}</span>
                    </button>

                    <ul class="dropdown-menu" style="width: 500px;">
                        <div class="row justify-content-center">
                            {% not_list user %}
                        </div>
                    </ul>


                </div>
                <div class="mx-1">
                    <p class="m-0 text-center">
                        <a class="p-2 text-white" href="{{ user.user_profile.get_absolute_url }}">
                            {{ user.username }}
                        </a>
                    </p>
                    <p class="m-0 text-center">
                        <span style="font-size: 9pt; font-weight: bold;">{{ user.user_profile.balance|floatformat:2 }} ₽ </span>
                        <a href="{% url 'core:pay_prepare' %}"> <i class="bi bi-patch-plus-fill text-success"></i></a>
                    </p>
                </div>

            {% else %}
                <a role="button" class="btn btn-outline-light border-0 mr-2" href="{% url 'account_signup' %}"
                   style="background-color: rgba(172,200,227,0.75);">Регистрация</a>
            {% endif %}

            {% if user.is_authenticated %}
                <button type="button" class="btn btn-outline-light mr-2 border-0" data-toggle="modal"
                        data-target="#logoutModal" style="background-color: rgb(172,200,227)">
                    Выход
                </button>
            {% else %}
                <button type="button" class="btn btn-outline-light border-0 mr-2" data-toggle="modal"
                        data-target="#loginModal" style="background-color: rgba(172,200,227,0.75);">
                    Вход
                </button>
            {% endif %}

            <form class="d-flex" action="{% url 'core:filter' %}" method="get" style="width: 23%">
                <input class="form-control mr-2" type="search" name="q" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-light border-0" type="submit" style="background-color: rgb(172,200,227)">
                    Поиск
                </button>
            </form>
        </div>


    </div>
</nav>

novells_site/templates/core/include/pay_prepare.html
{% extends 'core/home.html' %}
{% load static %}
{% load user_tags %}
{% block title %}
    Перевод китайских даньмэй-новелл Privereda1 | Пополнение баланса
{% endblock title %}

{% block content %}
    <div class="container-xxl">
        <div class="row d-flex justify-content-center mt-2">
            <div class="col-8">
                <form method="post" action="{% url 'core:donate_money' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Email-адрес для чека</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                               name="email">
                        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                    </div>
                    <div class="mb-3">
                        <label for="suminput" class="form-label">Сумма</label>
                        <input type="text" class="form-control" id="suminput" name="sum">
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                        <label class="form-check-label" for="exampleCheck1">Я согласен с условиями сделки</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Перейти к пополнению баланса</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}